version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

  ui-client:
    container_name: ui-client
    build:
      context: ./ui/
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  api-gateway:
    container_name: api-gateway
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    volumes:
      - '.:/data'
    ports:
      - '8762:8762'

  service-discovery:
    container_name: service-discovery
    build:
      context: ./service-discovery/
      dockerfile: Dockerfile
    volumes:
      - '.:/data'
    ports:
      - '8761:8761'

  project-service:
    container_name: project-service
    build:
      context: ./project-service/
      dockerfile: Dockerfile
    volumes:
      - '.:/data'
    ports:
      - '8763:8763'

    user-service:
      container_name: user-service
      build:
        context: ./user-service/
        dockerfile: Dockerfile
      volumes:
      - '.:/data'
      ports:
        - '8764:8764'