server:
  port: ${PORT:8762}

spring:
  application:
    name: api-gateway

zuul:
  ignoredServices: '*'
  routes:
    project-service:
      path: /api/projects/**
      serviceId: project-service
      stripPrefix: false
    user-service:
      path: /api/users/**
      serviceId: user-service
      stripPrefix: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false